name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test_on_chrome:
    name: Chrome Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3

      - name: Set node version
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Install Puppeteer
        run: npx puppeteer browsers install chrome

      - name: Find problems
        run: pnpm lint

      - name: Run tests
        run: pnpm test
